### ISSUE TITLE
배치파일 오류

### ISSUE THREAD

**Issue by gkamvva** [buYoung/webaim#1]
\hotkey.go:180:47: undefined: hotkey.None
\hotkey.go:189:49: undefined: hotkey.None
\hotkey.go:198:49: undefined: hotkey.None
\hotkey.go:207:51: undefined: hotkey.None
\hotkey.go:216:52: undefined: hotkey.None
\hotkey.go:225:51: undefined: hotkey.None
\hotkey.go:234:51: undefined: hotkey.None
\hotkey.go:243:53: undefined: hotkey.None
\hotkey.go:253:55: undefined: hotkey.None
\hotkey.go:262:51: undefined: hotkey.None
\hotkey.go:262:51: too many errors

**Comment by buYoung** [comment]
변경된 Readme 파일 읽어보시고 다시시도해주세요.

안되면 코멘트 달아주시구요

**Comment by gkamvva** [comment]
똑같은 오류가 뜹니다.

**Comment by gkamvva** [comment]
hotkey.go:5:2: cannot find package "github.com/MakeNowJust/hotkey" in any of:
        C:\Go\src\github.com\MakeNowJust\hotkey (from $GOROOT)
        ($GOPATH not set)
webserver.go:7:2: cannot find package "github.com/buYoung/webaim/aes256" in any of:
        C:\Go\src\github.com\buYoung\webaim\aes256 (from $GOROOT)
        ($GOPATH not set)
hotkey.go:6:2: cannot find package "github.com/buYoung/webaim/proccess" in any of:
        C:\Go\src\github.com\buYoung\webaim\proccess (from $GOROOT)
        ($GOPATH not set)
webserver.go:9:2: cannot find package "github.com/gin-gonic/gin" in any of:
        C:\Go\src\github.com\gin-gonic\gin (from $GOROOT)
        ($GOPATH not set)
main.go:8:2: cannot find package "github.com/lxn/win" in any of:
        C:\Go\src\github.com\lxn\win (from $GOROOT)
        ($GOPATH not set)
utility.go:4:2: cannot find package "golang.org/x/sys/windows/registry" in any of:
        C:\Go\src\golang.org\x\sys\windows\registry (from $GOROOT)
        ($GOPATH not set)

피시방에서 시도 했을경우 이렇게 나옵니다

**Comment by buYoung** [comment]
각종 문제 해결
